services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://mongo:UWxIyLcLqSLzUskMheYBSwdzqXjHYate@gondola.proxy.rlwy.net:30232/cep-app-database
      CLIENT_ORIGIN: http://localhost:3000
      BACKEND_URL: http://localhost:4000
    ports:
      - "4000:4000"
    volumes:
      - backend-uploads:/app/uploads
      - backend-logs:/app/logs

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:4000
    environment:
      NODE_ENV: production
      PORT: 3000
      VITE_API_BASE_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  backend-uploads:
  backend-logs:

